"""empty message

Revision ID: f1a19f6b0842
Revises: 
Create Date: 2017-12-02 18:47:28.777864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1a19f6b0842'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
	# ### commands auto generated by Alembic - please adjust! ###
	op.create_table(
		'user',
		sa.Column('id', sa.Integer(), nullable=False),
		sa.Column('email', sa.String(length=128), nullable=True),
		sa.PrimaryKeyConstraint('id'),
		sa.UniqueConstraint('email')
	)
	# ### end Alembic commands ###


def downgrade():
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_table('user')
	# ### end Alembic commands ###

