"""empty message
Revision ID: afdsfa34234
Revises: 
Create Date: 2017-12-02 19:40
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afdsfa34234'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
	# ### commands auto generated by Alembic - please adjust! ###
	op.create_table('user',
	sa.Column('id', sa.Integer(), nullable=False),
	sa.Column('email', sa.String(length=128), nullable=True),
	sa.PrimaryKeyConstraint('id'),
	sa.UniqueConstraint('email')
)


def downgrade():
	op.drop_table('user')
